# Generated by Django 2.2.12 on 2022-07-14 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_title', models.CharField(max_length=100)),
                ('ep_title', models.CharField(max_length=150)),
                ('ep_season', models.IntegerField()),
                ('ep_number', models.IntegerField()),
                ('user_headline', models.CharField(max_length=100)),
            ],
        ),
    ]
