# Generated by Django 2.2.12 on 2022-07-17 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=500)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Episode')),
            ],
        ),
    ]
