# Generated by Django 2.2.12 on 2022-07-21 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_review_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('played_by', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=75)),
            ],
        ),
        migrations.AddField(
            model_name='episode',
            name='characters',
            field=models.ManyToManyField(to='main_app.Character'),
        ),
    ]
